config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: "public/homes#top"
  get "/about" => "public/homes#about"

  # ユーザー用
  devise_for :users, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: "public/sessions"
  }

  # 管理者用
  devise_for :admin,  skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions",
  }

  scope module: :public do
    patch "users/withdrawal" => "users#withdrawal", as: "withdrawal_user"
    get "users/check" => "users#check", as: "check_user"
    resources :users, only: [:show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get 'followers' => 'relationships#followers', as: 'followers'
      get 'following' => 'relationships#following', as: 'following'
    end
    resources :episodes, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      resource :favourite, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    resources :notifications, only: [:index]
    resources :searches, only: [:index]
    resources :categories, only: [:show]
    get "/categories/subcategories" => "categories#subcategories"
    get "/tag/:name", to: "episodes#hashtag"
    get "/favourites/index" => "favourites#index", as: "favourites_index"
  end

  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update]
    resources :episodes, only: [:index, :show, :edit, :update, :destroy] do
      resources :comments, only: [:destroy]
    end
    resources :searches, only: [:index]
    resources :categories, only: [:index, :create, :edit, :update, :destroy]
  end

  devise_scope :user do
    post "users/guest_sign_in" => "users/sessions#guest_sign_in"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/searches_controller.rb
# frozen_string_literal: true

class Admin::SearchesController < ApplicationController
  before_action :authenticate_admin!
  def index
    @query = params[:query]
    @users = User.where("name LIKE ?", "%#{@query}%").order("created_at DESC")
    @episodes = Episode.where("title LIKE ?", "%#{@query}%").order("created_at DESC")
  end
end

app/helpers/admin/searches_helper.rb
# frozen_string_literal: true

module Admin::SearchesHelper
end

app/views/admin/searches/_episode_index.html.erb
<h2 class="h4 text-center mx-auto mb-4">エピソード一覧</h2>
<div class="mx-auto col-10">
  <table class="table">
    <thead>
      <tr>
        <td>ID</td>
        <td>アカウント名</td>
        <td>タイトル</td>
        <td>公開ステータス</td>
      </tr>
    </thead>
    <tbody>
      <% episodes.each do |episode| %>
      <tr>
        <td><%= episode.id %></td>
        <td><%=  link_to episode.user.name, admin_user_path(episode.user), class: "text-body" %></td>
        <td><u><%= link_to episode.title, admin_episode_path(episode), class: "text-body d-inline-block text-truncate font-weight-bold" %></u></td>
        <td><%= Episode.visibilities_i18n[episode.visibility] %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/admin/searches/_user_index.html.erb
<h2 class="h4 text-center mx-auto mb-4">ユーザー一覧</h2>
<div class="mx-auto col-10">
  <table class="table">
    <thead>
      <tr>
        <td>ID</td>
        <td><span class="d-none d-lg-block">アカウント名</span></td>
        <td>email</td>
        <td><span class="d-none d-lg-block">公開ステータス</span></td>
        <td><span class="d-none d-lg-block">退会ステータス</span></td>
      </tr>
    </thead>
    <tbody>
      <% users.each do |user| %>
        <tr>
          <td><%= user.id %></td>
          <td><u><%= link_to user.name, admin_user_path(user), class: "text-body font-weight-bold" %></u></td>
          <td><%= user.email %></td>
          <% if user.is_public == true %>
            <td><strong>公開</strong></td>
          <% else %>
            <td><strong>非公開</strong></td>
          <% end %>
          <% if user.is_active == true %>
            <td class="text-success"><strong>有効</strong></td>
          <% else %>
            <td class="text-muted"><strong>退会</strong></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/searches/index.html.erb
<div class="container">
  <h1 class="h4 row">"<%= @query %>"の検索結果</h1>
  <% if @users.exists? %>
    <%= render "user_index", users: @users %>
  <% end %>
  <% if @episodes.exists? %>
    <%= render "episode_index", episodes: @episodes %>
  <% end %>
  
  <% if @users.empty? && @episodes.empty? %>
    <div class="d-flex justify-content-center align-items-center" style="height: 60vh;">
      <p class="h4">該当するものはありませんでした。</p>
    </div>
  <% end %>
</div>