config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: "public/homes#top"
  get "/about" => "public/homes#about"

  # ユーザー用
  devise_for :users, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: "public/sessions"
  }

  # 管理者用
  devise_for :admin,  skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions",
  }

  scope module: :public do
    patch "users/withdrawal" => "users#withdrawal", as: "withdrawal_user"
    get "users/check" => "users#check", as: "check_user"
    resources :users, only: [:show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get 'followers' => 'relationships#followers', as: 'followers'
      get 'following' => 'relationships#following', as: 'following'
    end
    resources :episodes, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      resource :favourite, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    resources :notifications, only: [:index]
    resources :searches, only: [:index]
    resources :categories, only: [:show]
    get "/categories/subcategories" => "categories#subcategories"
    get "/tag/:name", to: "episodes#hashtag"
    get "/favourites/index" => "favourites#index", as: "favourites_index"
  end

  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update]
    resources :episodes, only: [:index, :show, :edit, :update, :destroy] do
      resources :comments, only: [:destroy]
    end
    resources :searches, only: [:index]
    resources :categories, only: [:index, :create, :edit, :update, :destroy]
  end

  devise_scope :user do
    post "users/guest_sign_in" => "users/sessions#guest_sign_in"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :category_relations, dependent: :destroy
  has_many :episodes, through: :category_relations


  with_options presence: true do
    validates :name
  end

  enum parent: { emotion: 0, genre: 1, year: 2 }
end

app/controllers/admin/categories_controller.rb
# frozen_string_literal: true

class Admin::CategoriesController < ApplicationController
  before_action :authenticate_admin!

  def index
    @categories = Category.all
    @category = Category.new
  end

  def create
    category = Category.new(category_params)
    if category.save
      flash[:notice] = "カテゴリーを追加しました"
      redirect_to admin_categories_path
    else
      render admin_categories_path
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = "カテゴリーを更新しました"
      redirect_to admin_categories_path
    else
      render :edit
    end
  end

  def destroy
    category = Category.find(params[:id])
    category.destroy
    redirect_to admin_categories_path
  end


  private
    def category_params
      params.require(:category).permit(:name, :parent)
    end

    def is_matching_login_user
      # 管理者ログインは認証済み
    end
end

app/helpers/admin/categories_helper.rb
# frozen_string_literal: true

module Admin::CategoriesHelper
end

app/views/admin/categories/_form.html.erb
  <div class="col">
    <%= form_with model: category, url: (action_name == 'edit' ? admin_category_path : admin_categories_path) do |f| %>
      <div class="d-flex flex-column flex-lg-row justify-content-lg-center my-4">
        <%= f.label :parent, "親カテゴリー", class: "col-lg-4 col-form-label font-weight-bold" %>
        <%= f.select :parent, Category.parents_i18n.invert, {prompt: '選択してください'}, class: 'col-lg-5 form-control' %>
      </div>
      <div class="d-flex flex-column flex-lg-row justify-content-lg-center my-4">
        <%= f.label :name, "カテゴリー名", class: "col-lg-4 col-form-label font-weight-bold" %>
        <%= f.text_field :name, class: 'col-lg-5 form-control', placeholder: 'カテゴリー名' %>
      </div>
      <div class="d-flex justify-content-center mt-4">
        <%= f.submit (action_name == 'edit' ? '更新' : '登録'), class: 'btn btn-primary px-4' %>
      </div>
    <% end %>
  </div>

app/views/admin/categories/_modal.html.erb
<span type="button" data-toggle="modal" data-target="#deleteCategory" class='btn btn-danger px-3'>
  削除
</span>

<div class="modal fade" id="deleteCategory" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-body">
        このカテゴリーを削除しますか？
      </div>
      <div class="modal-footer border-0">
        <button type="button" class="btn btn-sm btn-secondary" data-dismiss="modal">戻る</button>
        <%= link_to  "削除する", admin_category_path(category), method: :delete, class: "btn btn-sm btn-danger" %>
      </div>
    </div>
  </div>
</div>

app/views/admin/categories/edit.html.erb
<div class="container">
  <h1 class="h4 text-center mb-4">カテゴリ編集</h1>
  <div class="row justify-content-center">
    <div class="col-lg-10">
      <div class="px-1">
        <%= render 'layouts/error_messages', resource: @category %>
      </div>
      <%= render 'form', category: @category %>
    </div>
  </div>
</div>

app/views/admin/categories/index.html.erb
<div class="container">
  <h1 class="h4 text-center mb-5">カテゴリー一覧・追加</h1>
  <%= render 'layouts/error_messages', resource: @category %>
  <div class="row justify-content-center mb-5">
    <%= render 'form', category: @category %>
  </div>

    <div class="row justify-content-center">
      <div class="col-8 mt-4">
        <table class="table table-bordered">
          <thead>
            <tr>
              <th class="bg-light col-1">ID</th>
              <th class="bg-light col-3">親カテゴリ</th>
              <th class="bg-light col-3">カテゴリ名</th>
              <th class="bg-light col-2"></th>
            </tr>
          </thead>
          <tbody>
            <% @categories.each do |category| %>
              <tr>
                <td><%= category.id %></td>
                <td><%= Category.parents_i18n[category.parent] %></td>
                <td><%= category.name %></td>
                <td>
                  <%= link_to '編集', edit_admin_category_path(category), class: 'btn btn-success px-3' %>
                  <%= render 'admin/categories/modal', category: category %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>

  </div>