config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: "public/homes#top"
  get "/about" => "public/homes#about"

  # ユーザー用
  devise_for :users, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: "public/sessions"
  }

  # 管理者用
  devise_for :admin,  skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions",
  }

  scope module: :public do
    patch "users/withdrawal" => "users#withdrawal", as: "withdrawal_user"
    get "users/check" => "users#check", as: "check_user"
    resources :users, only: [:show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get 'followers' => 'relationships#followers', as: 'followers'
      get 'following' => 'relationships#following', as: 'following'
    end
    resources :episodes, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      resource :favourite, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    resources :notifications, only: [:index]
    resources :searches, only: [:index]
    resources :categories, only: [:show]
    get "/categories/subcategories" => "categories#subcategories"
    get "/tag/:name", to: "episodes#hashtag"
    get "/favourites/index" => "favourites#index", as: "favourites_index"
  end

  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update]
    resources :episodes, only: [:index, :show, :edit, :update, :destroy] do
      resources :comments, only: [:destroy]
    end
    resources :searches, only: [:index]
    resources :categories, only: [:index, :create, :edit, :update, :destroy]
  end

  devise_scope :user do
    post "users/guest_sign_in" => "users/sessions#guest_sign_in"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :image
  # validate :image_size_validation

  has_many :episodes, dependent: :destroy
  has_many :favourites, dependent: :destroy
  has_many :favourite_episodes, through: :favourites, source: :episode
  has_many :comments, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :notifications, as: :recipient

  # accepts_nested_attributes_for :categroy_relations

  validates :name, presence: true, length: { minimum: 2, maximum: 20 }
  # 半角英数字のみを許可する正規表現（英字は小文字のみ）
  ALPHANUMERIC_REGEX = /\A[a-z0-9]+\z/
  validates :username, presence: true, length: { minimum: 2, maximum: 20 }, uniqueness: true, format: { with: ALPHANUMERIC_REGEX }
  validates :introduction, length: { maximum: 400 }
  validates :email, uniqueness: true

  # ユーザー画像サイズ変換
  def get_profile_image(width, height)
    unless image.attached?
      file_path = Rails.root.join("app/assets/images/no_image.jpg")
      image.attach(io: File.open(file_path), filename: "default-image.jpg", content_type: "image/jpeg")
    end
    image.variant(resize_to_fill: [width, height]).processed
  end

  def followed_by?(user)
    passive_relationships.exists?(follower_id: user.id)
  end


  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲストユーザー"
      user.username = "guest"
      user.birthdate = "2023-07-01"
    end
  end

  def guest_user?
    email == GUEST_USER_EMAIL
  end

  # ユーザーの有効性を検証
  def active_for_authentication?
    super && (self.is_active == true)
  end

  # def image_size_validation
  #   if image.attached?
  #     if image.blob.byte_size > 1.megabytes
  #       image.purge
  #       errors.add(:image, "は1MB以下でなければなりません")
  #     end
  #   end
  # end
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @users = User.page(params[:page]).per(10)
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "#{@user.name}さんの会員情報が更新されました。"
      redirect_to admin_user_path(params[:id])
    else
      flash.now[:alert] = "未記入項目があります"
      render :edit
    end
  end

  private
    def user_params
      params.require(:user).permit(:image, :name, :username, :birthdate, :email, :introduction, :is_public, :is_active)
    end

    # 管理者機能では編集先のidとの一致を求めない
    def is_matching_login_user
    end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: "guestuserでログインしました。"
  end
end

app/helpers/admin/users_helper.rb
# frozen_string_literal: true

module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="container">
  <h1 class="h4 text-center"><%= @user.name %>さんのユーザー情報編集</h1>
  <div class="col-11 mx-auto">
    <%= render 'layouts/error_messages', resource: @user %>
      <%= form_with model: @user, url: admin_user_path do |f| %>

        <div class="form-group row ml-3 my-4">
          <label class="col-lg-3 col-form-label font-weight-bold pl-0">ユーザーID</label>
          <div class="col-lg-9 form-row align-items-center">
              <%= @user.id %>
          </div>
        </div>

        <div class="form-group row ml-3 my-4">
          <label class="col-lg-3 col-form-label font-weight-bold pl-0">名前</label>
          <div class="col-lg-9 form-row">
            <%= f.text_field :name, class: "form-control" %>
          </div>
        </div>

        <div class="form-group row ml-3 my-4">
          <label class="col-lg-3 col-form-label font-weight-bold pl-0">ユーザーネーム</label>
          <div class="col-lg-9 form-row">
            <%= f.text_field :username, class: "form-control" %>
          </div>
        </div>

        <div class="form-group row ml-3 my-4">
          <label class="col-lg-3 col-form-label font-weight-bold pl-0">プロフィール</label>
          <div class="col-lg-9 form-row">
            <%= f.text_area :introduction, rows: 6, class: "form-control" %>
          </div>
        </div>

        <div class="form-group row ml-3 my-4">
          <label class="col-lg-3 col-form-label font-weight-bold pl-0">生年月日</label>
          <div class="col-lg-9 form-row">
            <%= f.date_field :birthdate, use_month_numbers: true, class: "form-control" %>
          </div>
        </div>

        <div class="form-group row ml-3 my-4">
          <label class="col-lg-3 col-form-label font-weight-bold pl-0">メールアドレス</label>
          <div class="col-lg-9 form-row">
            <%= f.email_field :email, class: "form-control" %>
          </div>
        </div>

        <div class="form-group row ml-3 my-4">
          <label class="col-lg-3 col-form-label font-weight-bold pl-0">公開ステータス</label>
          <div class="col-lg-9 form-row y-middle">
            <div class="col-5  d-flex align-items-center">
              <%= f.radio_button :is_public, true %>
              <%= f.label :is_public, "公開", value: true, class: "my-0 mr-3" %>
              <%= f.radio_button :is_public, false %>
              <%= f.label :is_public, "非公開", value: false, class: "m-0" %>
            </div>
          </div>
        </div>

        <div class="form-group row ml-3 my-4">
          <label class="col-lg-3 col-form-label font-weight-bold pl-0">アクティブステータス</label>
          <div class="col-lg-9 form-row y-middle">
            <div class="col-5  d-flex align-items-center">
              <%= f.radio_button :is_active, true %>
              <%= f.label :is_active, "有効", value: true, class: "my-0 mr-3" %>
              <%= f.radio_button :is_active, false %>
              <%= f.label :is_active, "退会", value: false, class: "m-0" %>
            </div>
          </div>
        </div>

        <div class="row justify-content-center">
          <div class="col-lg-9 form-row d-flex justify-content-center">
            <%= f.submit "変更を保存", class: "btn btn-success px-4" %>
          </div>
        </div>

    <% end %>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="container">
  <h1 class="h4 text-center mb-5">ユーザー一覧</h1>
  <div class="mx-auto col-12">
    <table class="table table-hover table-bordered">
      <thead class="text-center">
        <tr>
          <th class="bg-light">ユーザーID</td>
          <th class="bg-light">名前</td>
          <th class="bg-light">メールアドレス</td>
          <th class="bg-light">公開ステータス</td>
          <th class="bg-light">アクティブステータス</td>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
        <tr>
          <td><%= user.id %></td>
          <td class="font-weight-bold"><%= link_to user.name, admin_user_path(user), class: "text-body" %></td>
          <td><%= user.email %></td>
          <% if user.is_public == true %>
            <td class="text-center"><strong>公開</strong></td>
          <% else %>
            <td class="text-center"><strong>非公開</strong></td>
          <% end %>
          <% if user.is_active == true %>
            <td class="text-success text-center"><strong>有効</strong></td>
          <% else %>
            <td class="text-muted text-center"><strong>退会</strong></td>
          <% end %>
        </tr>
      <% end %>
    </body>
  </table>

    <div>
      <%= paginate @users %>
    </div>

  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container my-4 px-sm-1">
  <div class="px-1">
    <h1 class="h4 text-center mx-auto mb-4" style="width: 100%;"><%= @user.name %>さんの情報詳細</h1>
  </div>
   <div class="col-12 mt-3 mx-auto">
    <table class="table table-hover table-borderless mx-auto">
      <thead>
        <tr>
          <td class="col-3">
          </td>
          <td class="col-9">
          </td>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th>ユーザーID</th>
          <td><%= @user.id %></td>
        </tr>
        <tr>
          <th>名前</th>
          <td><%= @user.name %></td>
        </tr>
        <tr>
          <th>ユーザーネーム</th>
          <td>@<%= @user.username %></td>
        </tr>
        <tr>
          <th>プロフィール</th>
          <td><%= @user.introduction %></td>
        </tr>
        <tr>
          <th>生年月日</th>
          <td><%= @user.birthdate.strftime("%Y/%m/%d") %></td>
        </tr>
        <tr>
          <th>メールアドレス</th>
          <td><%= @user.email %></td>
        </tr>
        <tr>
          <th>公開ステータス</th>
          <% if @user.is_public == true %>
            <td><strong>公開</strong></td>
          <% else %>
            <td><strong>非公開</strong></td>
          <% end %>
        </tr>
        <tr>
          <th>アクティブステータス</th>
          <% if @user.is_active == true %>
            <td class="text-success"><strong>有効</strong></td>
          <% else %>
            <td class="text-muted"><strong>退会</strong></td>
          <% end %>
        </tr>
        <th></th>
        <td>
          <%= link_to "編集する", edit_admin_user_path(@user), class: "btn btn-success btn-sm mr-2 mr-md-5 px-4" %>
          <%#= link_to "投稿一覧を見る", admin_user_episodes_path(@user), class: "btn btn-primary btn-sm px-2 mt-2 mt-sm-0"  %>
        </td>

      </tbody>
    </table>
  </div>
</div>