config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: "public/homes#top"
  get "/about" => "public/homes#about"

  # ユーザー用
  devise_for :users, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: "public/sessions"
  }

  # 管理者用
  devise_for :admin,  skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions",
  }

  scope module: :public do
    patch "users/withdrawal" => "users#withdrawal", as: "withdrawal_user"
    get "users/check" => "users#check", as: "check_user"
    resources :users, only: [:show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get 'followers' => 'relationships#followers', as: 'followers'
      get 'following' => 'relationships#following', as: 'following'
    end
    resources :episodes, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      resource :favourite, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    resources :notifications, only: [:index]
    resources :searches, only: [:index]
    resources :categories, only: [:show]
    get "/categories/subcategories" => "categories#subcategories"
    get "/tag/:name", to: "episodes#hashtag"
    get "/favourites/index" => "favourites#index", as: "favourites_index"
  end

  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update]
    resources :episodes, only: [:index, :show, :edit, :update, :destroy] do
      resources :comments, only: [:destroy]
    end
    resources :searches, only: [:index]
    resources :categories, only: [:index, :create, :edit, :update, :destroy]
  end

  devise_scope :user do
    post "users/guest_sign_in" => "users/sessions#guest_sign_in"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false" class="alert alert-warning">
    <h1 class="h4">
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h1>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_message.html.erb
<% flash.each do |message| %>
  <div class="alert alert-<%= bootstrap_alert(message[0]) %> alert-dismissible fade show">
    <% if message[1].is_a?(Array) %>
      <% message[1].each do |value| %>
        <span><%= value %><br></span>
      <% end %>
    <% else %>
      <span><%= message[1] %></span>
    <% end %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <nav class="navbar navbar-expand-md navbar-light">
    <ul class="navbar-nav mx-auto">
      <% if user_signed_in? %>
        <%# ログイン後 %>
        <li class="nav-item"><%= link_to "サイト概要", about_path, class: "nav-link" %></li>
      <% elsif admin_signed_in?%>
        <!--管理者ログイン後-->
        管理者ログイン中
      <% else %>
        <%# ログイン前 %>
        <div class="d-flex justify-content-end">
          <div class="col">
            <small><%= link_to "管理者ログイン", new_admin_session_path, class: "nav-link" %></small>
          </div>
        </div>
      <% end %>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="header">
  <nav class="navbar navbar-expand-lg navbar-light">
    <%= link_to root_path, class: "logo" do %>
      <%= image_tag("episoda_logo.png", alt: "logo", id: "header_logo", class: "logo") %>
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                  aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div  class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto">
        <%# ログイン後 %>
        <% if user_signed_in? %>
          <%= render 'layouts/user' %>
        <% elsif admin_signed_in? %>
        <!--管理者ログイン後-->
          <li class="nav-link"><%= link_to "ユーザー一覧", admin_users_path, class: "nav-link" %></li>
          <li class="nav-link"><%= link_to "エピソード一覧", admin_episodes_path, class: "nav-link" %></li>
          <li class="nav-link"><%= link_to "カテゴリー一覧", admin_categories_path, class: "nav-link" %></li>
          <!--<li class="nav-link"><%#= link_to "グループ一覧", root_path, class: "nav-link" %></li>-->
          <li class="nav-link"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "nav-link" %></li>
        <% else %>
          <%# ログイン前 %>
          <li class="nav-link"><%= link_to "アバウトページ", about_path, class: "nav-link" %></li>
          <li class="nav-link"><%= link_to "ログイン", new_user_session_path, class: "nav-link" %></li>
          <li class="nav-link"><%= link_to "新規登録", new_user_registration_path, class: "nav-link" %></li>
        <% end %>
        <!--検索機能-->
        <% if user_signed_in? || admin_signed_in? %>
           <%= render "layouts/search" %>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/_search.html.erb
<div class="form-inline my-2 justify-content-center ml-1">
  <%= form_with url: admin_signed_in? ? admin_searches_path : searches_path, method: :get do |f| %>
    <div class="row">
      <div class="col pr-0 mt-1">
        <%= f.text_field :query, placeholder: "Search", class: "form-control-sm"%>
      </div>
      <div class="col pl-1 mt-1">
        <button class="btn btn-secondary btn-sm">
          <i class="fa-solid fa-magnifying-glass"></i>
        </button>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/_user.html.erb
<!--お知らせ-->
<li class="nav-link">
  <% if current_user.notifications.unread.where('created_at >= ?', 7.days.ago).exists? %>
    <!--新規通知あり-->
    <%= link_to notifications_path, class: "nav-link", data: { toggle: "tooltip", placement: "top" }, title: "お知らせ" do %>
      <i class="fa-regular fa-bell fa-lg" style="color: #f05656;"></i>
    <% end %>
  <% else %>
    <!--新規通知なし-->
    <%= link_to notifications_path, class: "nav-link", data: { toggle: "tooltip", placement: "top" }, title: "お知らせ" do %>
      <i class="fa-regular fa-bell fa-lg"></i>
    <% end %>
  <% end %>
</li>
<!--マイページ-->
<li class="nav-link">
  <%= link_to user_path(current_user), class: "nav-link", data: { toggle: "tooltip", placement: "top" }, title: "マイページ" do %>
    <i class="fa-solid fa-circle-user fa-lg"></i>
  <% end %>
  </li>
  <!--新規投稿-->
  <li class="nav-link">
  <%= link_to new_episode_path, class: "nav-link", data: { toggle: "tooltip", placement: "top" }, title: "新規投稿" do %>
    <i class="fa-solid fa-pen-to-square fa-lg"></i>
  <% end %>
</li>
<!--ユーザー情報編集-->
<li class="nav-link">
  <%= link_to edit_user_path(current_user), class: 'nav-link', data: { toggle: "tooltip", placement: "top" }, title: "ユーザー編集" do %>
    <i class="fa-solid fa-gear fa-lg"></i>
  <% end %>
</li>
<li class="nav-link"><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link font-weight-bold" %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Episoda</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/7ad12159d4.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'dataC-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="header">
      <%= render "layouts/header" %>
    </div>
    <div id="flash-message">
      <%= render "layouts/flash_message" %>      
    </div>
    <main>
      <%= yield %>
    </main>
    <div class="footer">
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>